//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaRun.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMC_ProjectOrder
    {
        public int OrderId { get; set; }
        public string TreeId { get; set; }
        public Nullable<int> ProjectDemandId { get; set; }
        public string OrderNumbering { get; set; }
        public string Icon { get; set; }
        public Nullable<decimal> OrderBudget { get; set; }
        public Nullable<int> IsReview { get; set; }
        public string ReviewMan { get; set; }
        public Nullable<System.DateTime> ReviewTime { get; set; }
        public Nullable<int> IsSubmit { get; set; }
        public string SubmitMan { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public Nullable<int> ConfirmOrder { get; set; }
        public string ConfirmMan { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateMan { get; set; }
        public Nullable<int> DeleteFlag { get; set; }
        public Nullable<int> Productioned { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public string Description { get; set; }
        public Nullable<int> Priority { get; set; }
        public string EngineeringPosition { get; set; }
        public string TreeName { get; set; }
    }
}
