//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaRun.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMC_MemberLibrary
    {
        public string MemberId { get; set; }
        public int MarkId { get; set; }
        public string EngineeringId { get; set; }
        public string Category { get; set; }
        public string MemberName { get; set; }
        public string MemberNumbering { get; set; }
        public string UnitId { get; set; }
        public string UnitPrice { get; set; }
        public string CAD_Drawing { get; set; }
        public string Model_Drawing { get; set; }
        public Nullable<int> IsRawMaterial { get; set; }
        public Nullable<int> IsProcess { get; set; }
        public string Icon { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<int> IsReview { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public string FullPath { get; set; }
        public Nullable<decimal> MemberWeight { get; set; }
        public string Description { get; set; }
    
        public virtual RMC_SubProject RMC_SubProject { get; set; }
    }
}
