//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaRun.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMC_MemberProcess
    {
        public int MemberProcessId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string ProcessName { get; set; }
        public string OperationTime { get; set; }
        public string ProcessRequirements { get; set; }
        public string Description { get; set; }
        public Nullable<int> SortCode { get; set; }
        public string ProcessMan { get; set; }
    }
}
