//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaRun.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMC_ShipManagement
    {
        public int ShipId { get; set; }
        public string TreeId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> MemberClassId { get; set; }
        public string MemberId { get; set; }
        public string MemberNumbering { get; set; }
        public string MemberModel { get; set; }
        public string MemberName { get; set; }
        public string ShipNumber { get; set; }
        public Nullable<int> IsPackaged { get; set; }
        public string UnitPrice { get; set; }
        public string TotalPrice { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ShipMan { get; set; }
        public string LogisticsStatus { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingTEL { get; set; }
        public string ShippingMan { get; set; }
        public string Description { get; set; }
        public Nullable<int> LibraryNumber { get; set; }
        public string ShipNumbering { get; set; }
    }
}
