//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaRun.Data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeaRunFramework_Base_2016Entities : DbContext
    {
        public LeaRunFramework_Base_2016Entities()
            : base("name=LeaRunFramework_Base_2016Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RMC_MemberLibrary> RMC_MemberLibrary { get; set; }
        public virtual DbSet<RMC_SubProject> RMC_SubProject { get; set; }
    }
}
